puts "🌱 Seeding spices..."

# Seed your database here

Food.create(name: 'Wheat Bread', calories: 69, category: 'bread', image: 'https://www.seasonsandsuppers.ca/wp-content/uploads/2020/11/honey-wheat-1200.jpg')
Food.create(name: 'White Bread', calories: 79, category: 'bread', image: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fassets.marthastewart.com%2Fd27%2Fhomemade_white_bread_how-to%2Fhomemade_white_bread_how-to_horiz.jpg')
Food.create(name: 'Rye Bread', calories: 65, category: 'bread', image: 'https://www.occasionallyeggs.com/wp-content/uploads/2020/08/Dark-Rye-Bread-2-1.jpg')
Food.create(name: 'Sourdough Bread', calories: 185, category: 'bread', image: 'https://heartbeetkitchen.com/foodblog/wp-content/uploads/2020/04/basic-sourdough-bread-recipe4.jpg')
Food.create(name: 'Dutch Crunch Bread', calories: 70, category: 'bread', image: 'https://ww2.kqed.org/app/uploads/sites/10/2020/07/IMG_2432-800x600.jpg')
Food.create(name: 'Multigrain Bread', calories: 80, category: 'bread', image: 'https://static.toiimg.com/thumb/76626392.cms?width=1200&height=900')
Food.create(name: 'Egg', calories: 78, category: 'protein', image: 'https://media.istockphoto.com/photos/lots-of-eggs-picture-id1169550679?s=612x612')
Food.create(name: 'Butter', calories: 100, category: 'dairy', image: 'https://solidstarts.com/wp-content/uploads/Butter-for-Babies-scaled.jpg')
Food.create(name: 'Ketchup', calories: 20, category: 'condiment', image: 'https://m.media-amazon.com/images/I/71b0CQV4SFS._SX425_.jpg')
Food.create(name: 'Maple Syrup', calories: 100, category: 'condiment', image: 'https://ii.worldmarket.com/fcgi-bin/iipsrv.fcgi?FIF=/images/worldmarket/source/65541_XXX_v1.tif&wid=2000&cvt=jpeg')
Food.create(name: 'Mayonnaise', calories: 100, category: 'condiment', image: 'https://m.media-amazon.com/images/I/81MoLlbTRBL._SL1500_.jpg')
Food.create(name: 'Ranch', calories: 120, category: 'dressing', image: 'https://images.heb.com/is/image/HEBGrocery/000163636?fit=constrain,1&wid=800&hei=800&fmt=jpg&qlt=85,0&resMode=sharp2&op_usm=1.75,0.3,2,0')
Food.create(name: 'Hot Sauce', calories: 0, category: 'condiment', image: 'https://m.media-amazon.com/images/I/71Ky8f8ZFmL._SL1500_.jpg')
Food.create(name: 'Bell Pepper', calories: 37, category: 'vegetable', image: 'https://i2.wp.com/chilipeppermadness.com/wp-content/uploads/2019/08/Bell-Peppers.jpg')
Food.create(name: 'Broccoli', calories: 31, category: 'vegetable', image: 'https://solidstarts.com/wp-content/uploads/Broccoli_edited-scaled.jpg')
Food.create(name: 'Onion', calories: 45, category: 'vegetable', image: 'https://i5.walmartimages.com/asr/33813ffc-7fc4-4ff5-8667-897307ca4054_3.c1faf49fe38fb5e447847773284aaafd.jpeg')
Food.create(name: 'Tomato', calories: 16, category: 'vegetable', image: 'https://post.healthline.com/wp-content/uploads/2020/09/tomatoes-1200x628-facebook-1200x628.jpg')
Food.create(name: 'White Rice', calories: 206, category: 'grain', image: 'https://www.simplyrecipes.com/thmb/81bMTasFf0D_XEpA_ZtoZeL27SY=/2000x1331/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2020__02__HTC-White-Rice-Lead-4-e5743ee4c63a40a0aec2f3abd9f1c097.jpg')
Food.create(name: 'Brown Rice', calories: 216, category: 'grain', image: 'https://cdn.loveandlemons.com/wp-content/uploads/2020/01/how-to-cook-brown-rice.jpg')
Food.create(name: 'Lentils', calories: 150, category: 'grain', image: 'https://www.jessicagavin.com/wp-content/uploads/2018/01/cooked-lentils-on-spoon-1200.jpg')
Food.create(name: 'Quinoa', calories: 222, category: 'grain', image: 'https://cdn.loveandlemons.com/wp-content/uploads/2019/09/quinoa.jpg')
Food.create(name: 'Black Beans', calories: 114, category: 'beans', image: 'https://cdn.loveandlemons.com/wp-content/uploads/2021/02/black-bean-recipes.jpg')
Food.create(name: 'Kidney Beans', calories: 225, category: 'beans', image: 'https://itsavegworldafterall.com/wp-content/uploads/2021/07/Kidney-Beans-2.jpg')
Food.create(name: 'White Beans', calories: 255, category: 'beans', image: 'https://images.media-allrecipes.com/userphotos/7060312.jpg')
Food.create(name: 'Lima Beans', calories: 217, category: 'beans', image: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2013/2/25/1/YW0210H_Baby-Lima-Beans_s4x3.jpg.rend.hgtvcom.616.462.suffix/1371614348577.jpeg')
Food.create(name: 'Pinto Beans', calories: 244, category: 'beans', image: 'https://addapinch.com/wp-content/uploads/2011/10/pinto-beans-recipe-0018.jpg')
Food.create(name: 'Banana', calories: 105, category: 'fruit', image: 'https://images.immediate.co.uk/production/volatile/sites/30/2017/01/Bananas-218094b-scaled.jpg')
Food.create(name: 'Avocado', calories: 234, category: 'fruit', image: 'https://i5.walmartimages.com/asr/098962b7-7d67-4ff5-a3c9-047c430f8fea_1.5847cdd72fa776356460d77b0b3c9301.jpeg')
Food.create(name: 'Strawberry', calories: 48, category: 'fruit', image: 'https://www.gardeningknowhow.com/wp-content/uploads/2021/07/ripe-red-strawberries.jpg')
Food.create(name: 'Grapes', calories: 62, category: 'fruit', image: 'https://m.media-amazon.com/images/S/assets.wholefoodsmarket.com//content/08/cc/7ce0dba74d8c82347bf2a26dc6fa/seasons-sweetest-grapes-hero.jpg')
Food.create(name: 'Apple', calories: 95, category: 'fruit', image: 'https://www.applesfromny.com/wp-content/uploads/2020/06/SnapdragonNEW.png')
Food.create(name: 'Chicken Breast', calories: 335, category: 'meat', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb_8mVVzoMRwUS4awEofZv8eaKg76jDfJbGvEZeLW1X99PPNKEjrBylTQ-DOGFWpIryBE&usqp=CAU')
Food.create(name: 'Chicken Thigh', calories: 206, category: 'meat', image: 'https://www.courtneyssweets.com/wp-content/uploads/2018/09/air-fryer-chicken-thighs-5.jpg')
Food.create(name: 'Chicken Wings', calories: 461, category: 'meat', image: 'https://hips.hearstapps.com/hmg-prod/images/classic-buffalo-wings-horizontal-279-1547506077.jpg')
Food.create(name: 'Beef Burger Patty', calories: 306, category: 'meat', image: 'https://res.cloudinary.com/hksqkdlah/image/upload/c_fill,dpr_3.0,f_auto,q_auto,w_200/15293_sil-burger-good')
Food.create(name: 'Turkey Burger Patty', calories: 170, category: 'meat', image: 'https://www.fifteenspatulas.com/wp-content/uploads/2013/05/Turkey-Burgers-Fifteen-Spatulas-5-640x427.jpg')
Food.create(name: 'Ribeye Steak', calories: 847, category: 'meat', image: 'https://girlscangrill.com/wp-content/uploads/2015/09/big-green-egg-ribeye.jpg')
Food.create(name: 'NY Strip Steak', calories: 250, category: 'meat', image: 'https://bakeitwithlove.com/wp-content/uploads/2020/05/Pan-Seared-New-York-Strip-Steak-lg-sq.jpg')
Food.create(name: 'Filet Mignon', calories: 278, category: 'meat', image: 'https://www.cookingclassy.com/wp-content/uploads/2020/12/filet-mignon-23.jpg')
Food.create(name: 'Potato', calories: 163, category: 'vegetable', image: 'https://s.yimg.com/ny/api/res/1.2/txS2.M4iIxMO9iP3pdNo9w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://s.yimg.com/os/creatr-uploaded-images/2021-05/17e8e370-ac03-11eb-beec-aa7670b0e0bb')
Food.create(name: 'Asparagus', calories: 27, category: 'vegetable', image: 'https://d47gxy3fatgwk.cloudfront.net/wp-content/uploads/2020/01/how-to-make-roasted-asparagus-355.jpg')
Food.create(name: 'Thousand Island Dressing', calories: 111, category: 'dressing', image: 'https://m.media-amazon.com/images/I/71ZGhjIlAML._SL1500_.jpg')
Food.create(name: 'Vinaigrette', calories: 72, category: 'dressing', image: 'https://m.media-amazon.com/images/I/71ihO0t6t4L._SL1500_.jpg')
Food.create(name: 'Bleu Cheese Dressing', calories: 31, category: 'dressing', image: 'https://i5.walmartimages.com/asr/2efe932c-193d-405d-9072-85507a12eab7.022f340d16edc48f0a67bc881dde42f7.jpeg')
Food.create(name: 'American Cheese', calories: 307, category: 'dairy', image: 'https://images.heb.com/is/image/HEBGrocery/001199858')
Food.create(name: 'Cheddar Cheese', calories: 403, category: 'dairy', image: 'https://cdn.shopify.com/s/files/1/0150/0232/products/Pearl_Valley_Sharp_Cheddar_Slices_large.jpg?v=1524073010')
Food.create(name: 'Colby Jack Cheese', calories: 384, category: 'dairy', image: 'https://images.heb.com/is/image/HEBGrocery/000081317?fit=constrain,1&wid=800&hei=800&fmt=jpg&qlt=85,0&resMode=sharp2&op_usm=1.75,0.3,2,0')
Food.create(name: 'Cottage Cheese', calories: 84, category: 'dairy', image: 'https://images.heb.com/is/image/HEBGrocery/000977110')
Food.create(name: 'Feta Cheese', calories: 265, category: 'dairy', image: 'https://i5.walmartimages.com/asr/eb204d04-2d5d-4aaa-bb82-494515d95498.4d56641ac021e9b1e0a818e1e5aa862b.jpeg')
Food.create(name: '2% Milk', calories: 103, category: 'dairy', image: 'https://i5.walmartimages.com/asr/cbcc26fb-af25-4672-bfb8-cb156cf1dadf_2.b93305e90bf7f66b9ab5f36f25652660.jpeg')
Food.create(name: 'Mozzarella Cheese', calories: 298, category: 'dairy', image: 'https://i5.walmartimages.com/asr/86028356-85fe-4a5d-b9e2-a2c544e7d177.e9a100b65e58a1b5ff9b5c179fbb9a7e.jpeg')
Food.create(name: 'Parmesan Cheese', calories: 392, category: 'dairy', image: 'https://m.media-amazon.com/images/I/71wpM-rJ2hL._SX522_.jpg')
Food.create(name: 'Velveeta Cheese', calories: 303, category: 'dairy', image: 'https://images.albertsons-media.com/is/image/ABS/960053589?$ecom-pdp-desktop$&defaultImage=Not_Available&defaultImage=Not_Available')
Food.create(name: 'Sour Cream', calories: 198, category: 'dairy', image: 'https://images.heb.com/is/image/HEBGrocery/000314020')

10.times {Meal.create()}



Eat.create(food_id: Food.first.id, meal_id: Meal.first.id)
Eat.create(food_id: Food.second.id, meal_id: Meal.first.id)
Eat.create(food_id: Food.third.id, meal_id: Meal.first.id)
Eat.create(food_id: Food.last.id, meal_id: Meal.first.id)
puts "✅ Done seeding!"
