puts "🌱 Seeding spices..."

# Seed your database here

Food.create(name: 'Wheat Bread', calories: 69, category: 'bread', image: '')
Food.create(name: 'White Bread', calories: 79, category: 'bread', image: '')
Food.create(name: 'Rye Bread', calories: 65, category: 'bread', image: '')
Food.create(name: 'Sourdough Bread', calories: 185, category: 'bread', image: '')
Food.create(name: 'Dutch Crunch Bread', calories: 70, category: 'bread', image: '')
Food.create(name: 'Multigrain Bread', calories: 80, category: 'bread', image: '')
Food.create(name: 'Egg', calories: 78, category: 'protein', image: 'https://www.google.com/search?q=calories+per+egg&sxsrf=AOaemvJl-05YNwtMhUFb_1_dCplgkwAgpw:1643145280183&tbm=isch&source=iu&ictx=1&vet=1&fir=QrE5ROPTj7EWlM%252CBIulLaDMjJ-M9M%252C%252Fm%252F033cnk%253BSPIvoxIlXWkpHM%252C1bnWKX6UE3NvdM%252C_%253BbUCb-l600uJ77M%252CFeHsFSixog9ySM%252C_%253BZcyZisj9cTdEjM%252CmyUJq7XUy9HtiM%252C_&usg=AI4_-kTrryldm3UJ0gOkNvCSK6PN2mu4gA&sa=X&ved=2ahUKEwiK1vSV6c31AhWwIjQIHXeoDoYQ_B16BAg2EAE#imgrc=QrE5ROPTj7EWlM')
Food.create(name: 'Butter', calories: 100, category: 'dairy', image: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fsolidstarts.com%2Fwp-content%2Fuploads%2FButter-for-Babies-scaled.jpg&imgrefurl=https%3A%2F%2Fsolidstarts.com%2Ffoods%2Fbutter%2F&tbnid=HDnX2Z44Ypk2QM&vet=12ahUKEwiH9v_f6c31AhWoGTQIHX9nAQoQMygAegUIARDwAg..i&docid=Bl25T5rxYy5HzM&w=2560&h=1920&itg=1&q=butter&ved=2ahUKEwiH9v_f6c31AhWoGTQIHX9nAQoQMygAegUIARDwAg')
Food.create(name: 'Ketchup', calories: 20, category: 'condiment', image: '')
Food.create(name: 'Maple Syrup', calories: 100, category: 'condiment', image: '')
Food.create(name: 'Mayonnaise', calories: 100, category: 'condiment', image: '')
Food.create(name: 'Ranch', calories: 120, category: 'dressing', image: '')
Food.create(name: 'Hot Sauce', calories: 0, category: 'condiment', image: 'https://www.google.com/imgres?imgurl=https%3A%2F%2Fi5.walmartimages.com%2Fasr%2F3b2679f3-a3fb-4811-a7a9-ba6e7170d071_1.6921ee184b150968d253220a9c3afbc3.jpeg&imgrefurl=https%3A%2F%2Fwww.walmart.com%2Fip%2FValentina-Mexican-Hot-Sauce-34-fl-oz%2F10422054&tbnid=mYAiE2r11wgHbM&vet=12ahUKEwiqvrjE6s31AhUtFTQIHTDwC1YQMygKegUIARCHAg..i&docid=RXC5QI-qbAcenM&w=2365&h=2365&itg=1&q=valentina%20nutrition%20facts&ved=2ahUKEwiqvrjE6s31AhUtFTQIHTDwC1YQMygKegUIARCHAg')
Food.create(name: 'Bell Pepper', calories: 37, category: 'vegetable', image: '')
Food.create(name: 'Broccoli', calories: 31, category: 'vegetable', image: '')
Food.create(name: 'Onion', calories: 45, category: 'vegetable', image: '')
Food.create(name: 'Tomato', calories: 16, category: 'vegetable', image: '')
Food.create(name: 'White Rice', calories: 206, category: 'grain', image: '')
Food.create(name: 'Brown Rice', calories: 216, category: 'grain', image: '')
Food.create(name: 'Lentils', calories: 150, category: 'grain', image: '')
Food.create(name: 'Quinoa', calories: 222, category: 'grain', image: '')
Food.create(name: 'Black Beans', calories: 114, category: 'beans', image: '')
Food.create(name: 'Kidney Beans', calories: 225, category: 'beans', image: '')
Food.create(name: 'White Beans', calories: 255, category: 'beans', image: '')
Food.create(name: 'Lima Beans', calories: 217, category: 'beans', image: '')
Food.create(name: 'Pinto Beans', calories: 244, category: 'beans', image: '')
Food.create(name: 'Banana', calories: 105, category: 'fruit', image: '')
Food.create(name: 'Avocado', calories: 234, category: 'fruit', image: '')
Food.create(name: 'Strawberry', calories: 48, category: 'fruit', image: '')
Food.create(name: 'Grapes', calories: 62, category: 'fruit', image: '')
Food.create(name: 'Apple', calories: 95, category: 'fruit', image: '')
Food.create(name: 'Chicken Breast', calories: 335, category: 'meat', image: '')
Food.create(name: 'Chicken Thigh', calories: 206, category: 'meat', image: '')
Food.create(name: 'Chicken Wings', calories: 461, category: 'meat', image: '')
Food.create(name: 'Beef Burger Patty', calories: 306, category: 'meat', image: '')
Food.create(name: 'Turkey Burger Patty', calories: 170, category: 'meat', image: '')
Food.create(name: 'Ribeye Steak', calories: 847, category: 'meat', image: '')
Food.create(name: 'NY Strip Steak', calories: 250, category: 'meat', image: '')
Food.create(name: 'Filet Mignon', calories: 278, category: 'meat', image: '')
Food.create(name: 'Potato', calories: 163, category: 'vegetable', image: '')
Food.create(name: 'Asparagus', calories: 27, category: 'vegetable', image: '')
Food.create(name: 'Thousand Island Dressing', calories: 111, category: 'dressing', image: '')
Food.create(name: 'Vinaigrette', calories: 72, category: 'dressing', image: '')
Food.create(name: 'Bleu Cheese Dressing', calories: 31, category: 'dressing', image: '')
Food.create(name: 'American Cheese', calories: 307, category: 'dairy', image: '')
Food.create(name: 'Cheddar Cheese', calories: 403, category: 'dairy', image: '')
Food.create(name: 'Colby Jack Cheese', calories: 384, category: 'dairy', image: '')
Food.create(name: 'Cottage Cheese', calories: 84, category: 'dairy', image: '')
Food.create(name: 'Feta Cheese', calories: 265, category: 'dairy', image: '')
Food.create(name: '2% Milk', calories: 103, category: 'dairy', image: '')
Food.create(name: 'Mozzarella Cheese', calories: 298, category: 'dairy', image: '')
Food.create(name: 'Parmesan Cheese', calories: 392, category: 'dairy', image: '')
Food.create(name: 'Velveeta Cheese', calories: 303, category: 'dairy', image: '')
Food.create(name: 'Sour Cream', calories: 198, category: 'dairy', image: '')



puts "✅ Done seeding!"
